travis:
  secure:
    BINSTAR_TOKEN: OLlNXj7l2ZSLHrURMipnMPPr1Xg/6kheqPKPmx+1R5nrj8RKWD06X7EvOfnbdpsysSx0WyOS57M25dgiVQG/8lPxYIcA8HM5W296rClJ0Mg5qezZEiiDWuZx3SBxqlVGo3uKOupGmzEGQFBtABXbTCS4Qo2t2YrGfQYGT4fodqNlWTV7vhFue38qjwWeXzKMkkxO/2mp44JMC9RD6FeqdPQCADe6ZrfpuGYgMMr5A0Q0D3JgJIlwenPVhk2b52J5b8ah8dIfo2yPDiMo7++awFulMv/wpQfbMhe/s3m7RHnrH3b74irVbIjdALaR0Cqe/IrpbBbq69MmcBt4im6HyJwdWXLjIqBA5gKlmddN+hMzRhWHfhiIAYgeN9/zer0PkTUfmB8XkaCxZf6UlcT3v2clNKBAZxuIzscJnuIFyKhCLuJkNFIfecSC1vfHg/k8ADMf3jaQAlHUGpgvmr3PelPSyQlCtV2bCHgGAwizt7ZfPHCb1msH/AWplHXOMNsjBRgYSp77hces8alOmn9YynYcKFNuPwIMm54kgOHVGy46rPZQfH6PtXKrR80z+EavYRdpC/TKFmLJ4GAn8b723yd864Zzho2DMO46gY3GCoKnDwzobpRWZNT8UUiHnrAFqIEu6M53DHi37bgsU+sWnoTYrIEymqVj6nU6/w3hggE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
