travis:
  secure:
    BINSTAR_TOKEN: aZzku88xIA1YohsUB64ZpMSJ4TF9AdUhfS+meVabp3wVV57RTjmk8q2Epj06L2F9CJXHP/i242B+0lkNPiKSAMTh3uq22FzciLqk31UlbAEmsroh29oz0XjxJR9oKybC+iNrZtrPR4GbnnAJol3o/ihviMO5dbkuLCgMZ/O2Kem8ZO8TS4XmA1Siov+mYtv7TmVxHNn0FBtTKPIEHWQ65xEYrjY/eTEyFQLoxwjZe8UWNi93haM8pTru1J48rQWtD2p+DGgFuQ4Nzu87qWGxLe2l2nmx9iAEBzhbO4E/ZGyV/Hx3G+kZU4jWXJd7w0C5sjfdfS/czOYmKg9attUOqttzx1T+bRweRcFFDPFDM24vbkaulDwyjZXyFjJj2C09jQ37+pWieFkJkqraNlLI0XWbEfZOQZZv4b/1aMYxsDacm3gLR5mHw1rwUmt75qm3pGxdSn16r/ThbpL4jcbT7CeMjZeuo43SOtBsClwc5Anj48AFEPo8IUKfetYmeaS/wcsYa/6D9c9KqSP7wmsYOPIrBchZj0viTjIBB4iGuTNiJQKN6WLqmICH+/O6fNbo8VaaXZilUVKClOv2suCSyIWJzg5T94HpsFp9/zT6Q1P3QRgV2Y6BfoBv+Dz+vJqw+XWsMs7xP6GKtPlFrXDJroBJYlAFOchZRje5LwMhERk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
