appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: W/q+PnRFkKwUXyUx2oViDitUr/OAsJeaLo8z+7y1C5D6HqlU+rYPGeJRsq5kbvwVBCOJEcaEXhIry5HkugQowzH4oqOj3NPKz2XKVLKXfpu0gAOoIZ+d0NHUGHI9mcpUvdHhhH6dpS8f9su4vT4wN4D2lkHcuYoXmHdJ+CDOqxQxEcYhT9SoRBwyhb5IxUxwtKlo4Nmhg755O5WijhD4ukLQmYlDLIGaTmsOOhR2TYMR4VSdAI3sgGBT2W0lYFVPX8sN9kiuA7sg5YPogmSV1gOyPggHIM/1jvsqyM4g/rwuV6ajjcfkLXvmnbklJMSkIvXN/ewSJVDijZgjtouoISwt1tokqj0mwCARl/8YF7zm8EC2Ov78SnYmKD6qVbrQLYFasWBhRrUjGZmDQ1z+HvjGlzR70tyJeIxurp0WrPnBCLM+qI4P5jVx9mr1zoZABOS3asL04ImZRjHR9iM6BhrAIJ3ATE4kC3IFjEk5S7lfzoRmfOLqmMPvdOaC5SgEW81ErUAGD9T9j4YjFBuCpxrZsqBc6UtOskZyJkqi68KTsmIswtVD7FXhUc1ZUUiBwF7kQrdnTLdTbE8SNldhygyL35LI8NtIXw9WjkupWuc6wgyf9AV/PNu/u5MVh/wrn6gPyyzmOp9fSumxX8aq/Xf71yOcrUH/In/MO1ub6/Q=}
