travis:
  secure:
    BINSTAR_TOKEN: mbZ4fkVXXUNjMtkfjLljU8AN+6206ALi3evZH2Q1hNNZ66lm72ouAfjCNcxtiqbLxo+sxzFeTPhowhEmoGu2GyRRTadzwiebQZhvUFuR3nO8c2B1L9ClEFjiD35EhdaDPeu51ccCSLUEFym6yLtrfY3p0eJnyIGOqg+r+i4V4ptmE+yHW5NPvgtKDmW6Z06t6QQZkM+T+0IsBp+aPfYx4vZ/QoCRWf3W+w5p83qTqtlw2rt5XYIMJN33XGr34ZqZkEoqHiW5KtOkFrZq42QyQlpHVinRU9hz0GOheyn/BlwKKkTj/ZQkpl7iBwgGny4MzgCZHW+7Sx4qyEoCdmOVihIIShdfBVLzNCMkSl6oANMMvyqvOdWBiQG45U6vVG9L/73plwL7DuI4WpqbVoZskleZJ1ZMT+6Pu/rmRbtkXJttZdoVznPrSPKIOuoKwrVnorIXkD8nBJc9cwEPef+tSVu3Fv17uPSuXBT9Lt6HQaiGmuMH9xz9ncwYZ6hj3OEo4wTVKiAq1ONKZD7gtLpzy0kYVq216rPMkyP3BOlQTaiyWFZQ24ht0kNlq63w9Cq1CszYT4kFg5hQLmW9NspymSpLHb5Szk0hkuwBGg5yR/MbZwlFcFpTGhRpfWMyOs9e1pZxgVAcWN9JL54dva/i9WMbseollO+KSmnFtolFoO8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
