travis:
  secure:
    BINSTAR_TOKEN: MFru5UlOyUgMmMWNIF4MiL1h92FNRCyL6mXDXL8duNwK9deyVIMYvKjY43AeReUIfEnrquequ7eK/dLx4H4gnD4IGDyEnMAB35IjCU9uGHF46jJlHYvhlKruXOuqXQPCDZk5OI2/R0wQFgLlMkycPRezy1NInc9HOVGNMYCaVxfW+TpkARUBWvrc4rQyDZ0XsxytoVWZHitsYtptOJBrHaUYwobT08O50prfrYy3Lf913TAbkLfGbxGdJOE7Yh9ZkWxgv96MbdegPUeSmFrVQwFgItmGDyvumBTwhL7MUCu6dhdQbnMckHbjCVz9rw9El04foL/NcLvon8B5RVNoDWpNJH74QXAUkAGjooF8+RqspAx36+Vv1D3g7Me1p1TCjhRCsjJ847/HVhI+e882gL/HdnUeQjxzbdN+JIcKn3qQGuj1zKMQkQl3mnwTGSHsZtISZsFHfU+loduHiHRhv6LLeK/KkXfeAOG8uDFI8OJQ9G6zds7SiyRFctT+mEcX8p1CrlkB9t4t9A9jEsTychXvxFjonL9Qvg3J/qqguJQUaaaKVwOanHy2BsGhuDBKsMkkXw6SXWR/FoNSqt+Fdct8q2OFIi0pteBzoIwZcEyjB2lKVnREHQwbxwDh6UEi/oD3tU/7i7KUfAiKx0EIgwoBedrBrs4NwiIaug0GP3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
